default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: mentor_match_development

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: mentor_match_test

